### ISSUE TITLE
Black screen and app crash without logs when packaged for Windows (64-bit)

### ISSUE THREAD

**Issue by qduborper** [getnamo/nodejs-ue4#10]
Hello,

thanks for this great plugin. I was able to make it work perfectly into the unreal engine editor in play mode.
But when I package my project for windows (64-built), then open the packaged app, the screen stay black for 1 min then the app close
I didn't had any error during the package build. And I don't see any error logs.
Do you have any recommendations for packaging settings ? 

thank you

**Comment by getnamo** [comment]
Packaging hasn't been addressed yet, see https://github.com/getnamo/nodejs-ue4/issues/6
