### ISSUE TITLE
update to version 4.24?

### ISSUE THREAD

**Issue by helghast** [getnamo/nodejs-ue4#11]
I got the following error when going to 4.24:
[https://forums.unrealengine.com/community/work-in-progress/1644397-node-js?p=1714980#post1714980](https://forums.unrealengine.com/community/work-in-progress/1644397-node-js?p=1714980#post1714980)

**Comment by getnamo** [comment]
Addressed with release: https://github.com/getnamo/nodejs-ue4/releases/tag/0.5.0, open new issue if new related problems appear
