### ISSUE TITLE
What would be required for a HTML5 build?

### ISSUE THREAD

**Issue by OliwerAntler** [getnamo/nodejs-ue4#13]
Hi! I really want to know how to make a HTML5 build possible?
Could this be used together with the Unreal JS to make that work maybe?

**Comment by getnamo** [comment]
node.js is based on some native modules which aren't exposed in HTML5 environment. The closest you can get is something like http://browserify.org/. In addition to that HTML5 has a very unknown way in which you map external dependencies like plugins into the platform, which means it would need some rather impossible changes to make it work for that platform (it also has been moved out of the engine in 4.24 into a 'platform extension', meaning you likely need an engine fork going forward).

The current platform this plugin supports is only Win64. It is likely both Linux and MacOS could be supported with a similar setup, and theoretically Android can run node.js but would need some big modifications to create a tighter bind. Beyond those platforms I don't currently see a reasonable path forward.

**Comment by OliwerAntler** [comment]
Thanks for a descriptive answer, that makes it much more clear as to what limitations there are. Felt that i really didnt understand to why it was not possible, as i couldn't find a good answer. Just want to say that the plugin works perfectly for the stuff i need it for. Great work :)
