### ISSUE TITLE
How to hide the script files

### ISSUE THREAD

**Issue by WailedParsley36** [getnamo/nodejs-ue4#38]
Hello, I wrote a firebase database and authentication script, but now I realised that if I package the game, users will see the scripts and can even modify it. 
So my question is how to hide the .js (script) files, or variables and how to disable modification of these files/vars.
If its not possible do you know some alternatives? Or a way to include Firebase SDK in Unreal? 

PS: I tried their REST API, but their auth token is not working

Thank you in advance.

**Comment by getnamo** [comment]
You could probably do a hash of the files you wish to stay fixed and then check against the hash before you run the script, if not matching, don't run it.

As for hiding the files, I'm not sure maybe you can use a minimizer e.g. https://www.npmjs.com/package/node-minify, but I'll admit I don't have much experience with this aspect yet.

**Comment by WailedParsley36** [comment]
Thank you for your very quick response. I totally forgot about the hashing option. I am an idiot.
I am sorry to bother you with this.
Have a nice day.
