### ISSUE TITLE
Packaging Support

### ISSUE THREAD

**Issue by getnamo** [getnamo/nodejs-ue4#6]
Will likely need to add scripts folder to packaging like https://github.com/getnamo/tensorflow-ue4/blob/master/Source/TensorFlow/TensorFlow.Build.cs#L28

**Comment by meignotn** [comment]
any ETA on this issues ? i tried to copy manualy the script folder into the package but it crashes

**Comment by helghast** [comment]
> any ETA on this issues ? i tried to copy manualy the script folder into the package but it crashes

I have the same problem.
Look at my message in the main thread: [https://forums.unrealengine.com/community/work-in-progress/1644397-node-js](url)

**Comment by getnamo** [comment]
I'll likely look into this issue sometime in January at earliest. In meantime the path is currently defined here: https://github.com/getnamo/nodejs-ue4/blob/master/Source/CommandLine/Private/NodeCmd.cpp#L40 changing this to reflect the location of the embedded ```ThirdParty/node``` content should suffice to make the plugin work in a packaged build (after copying third party folder over to that location after packaging)

**Comment by qduborper** [comment]
Hello! thanks for the quickfix. The game now starts but not the server instance. Do I need also to copy the Scripts folder to content ? 

thanks

**Comment by getnamo** [comment]
That sounds right. You should have both the third party folder and the scripts folder in the same relative folders as the project in the packaged folder for it to find everything

**Comment by getnamo** [comment]
Support added in https://github.com/getnamo/nodejs-ue4/commit/7fad399b536995b194e307285351541417790b2f

Instructions for packaging are found here: https://github.com/getnamo/nodejs-ue4#packaging 
- you only need to add your project script folder to the additional assets to copy, all plugin related content gets automatically copied

**Comment by getnamo** [comment]
Closing, open new issue if new packaging issues appear
